sudo: required

services:
  - docker

branches:
  only:
    - master

install:
  - docker build -t hnakamur/libvmodheaderrpm .

script:
  - docker run hnakamur/libvmodheaderrpm "$COPR_LOGIN" "$COPR_USERNAME" "$COPR_TOKEN"
