require 'rake'
require 'rspec/core/rake_task'
require 'colorize'
require 'rspec'

task :spec    => 'spec:all'
task :default => :spec

namespace :spec do
	RSpec::Core::RakeTask.new(:all) do |t|
		t.pattern = "spec/**/*_spec.rb"
	end
end
